# Setup
title:        Paolo Rodríguez
tagline:      Solutions Architect · Data Architect · Technology Consulting Manager
description:  Fourteen years of experience leading and implementing transformation programmes for nuclear, electricity, water, and gas utility companies. Specialises in end-to-end process delivery and governance.
url:          https://paolorodriguez.com
baseurl:      ''
permalink:    /:categories/:title
future:       false

# About/contact
author:
  name:       Paolo Rodríguez
  firstname:  Paolo
  lastname:   Rodríguez
  url:        https://paolorodriguez.com
  email:      hello@paolorodriguez.com

# Gems
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from

# Custom vars
version:              0.1.0
google_analytics_id:  # TBD

# Front-matter defaults
defaults:
  - scope:
      path:   ''
    values:
      locale: 'en-GB'
  - scope:
      path:   'en-gb'
    values:
      locale: 'en-GB'
  - scope:
      path:   'hi-in'
    values:
      locale: 'hi-IN'
  - scope:
      path:   'tl-ph'
    values:
      locale: 'tl-PH'

# Feed optiohs
feed:
  path: atom.xml

# Kramdown options
kramdown:
  toc_levels: "2"

# SASS options
sass:
  sass_dir:   _sass
  sourcemap:  development
  style:      compressed